config/routes.rb
Rails.application.routes.draw do

  resources :drawing

  

  
  root 'drawing#index'

  get 'error' => 'drawing#error'

end

app/models/drawing.rb
class Drawing < ActiveRecord::Base
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def welcome
    render text: "Web Board"
  end
end

app/controllers/drawing_controller.rb
class DrawingController < ApplicationController
  layout "application"

  respond_to :html, :json
  protect_from_forgery
  skip_before_action :verify_authenticity_token, if: :json_request?

  #root
  def index
    logger.debug request.base_url
  end

  #POST
  def create
    @drawing = Drawing.new
    @drawing.imgUrl = params[:dataURI]
    flash[:base_url] = request.base_url if @drawing.save
    render layout: "blank" and return
  end

  #GET, new drawing
  def new 
  end

  #GET, edit drawing
  def edit
    @drawing = Drawing.find_by(id: params[:id])
    if @drawing.present?
      render layout: "application" and return
    end
    redirect_to action: error
  end

  #GET, show static drawing
  def show
    @drawing = Drawing.find_by(id: params[:id])
    if @drawing.present?
      render layout: "static" and return
    end
    redirect_to action: error
  end

  #PATCH update
  def update

  end

  #PUT
  def update

  end

  #DELETE
  def destroy

  end

  def error
    # render layout: "static" and return
  end

  protected

  def json_request?
    request.format.json?
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/drawing_helper.rb
module DrawingHelper
end

app/views/drawing/create.html.erb
  <% if @drawing %>
    <h3 class="flex">Share your drawing</h3>
    <h2 class="flex">Link to editable image:</h2><%= link_to "#{ flash[:base_url] }#{edit_drawing_path(@drawing.id)}", edit_drawing_path(@drawing.id), :class => "flex"%>
    <h2 class="flex">Link to static image:</h2> <%= link_to "#{ flash[:base_url] }#{ drawing_path(@drawing.id) }", drawing_path(@drawing.id), :class => "flex"%>
    &nbsp
    <!-- <%= link_to "Start a new Image", flash[:base_url], :class => "flex"%> -->
    <%= link_to flash[:base_url] do%>
      <h2 class="flex">Start a new image.</h2>
    <% end %>
    

  <% else %>
  <h3>Something went wrong, your image didn't save.</h3>
  <% end %>

app/views/drawing/edit.html.erb
<%= image_tag(@drawing.imgUrl, :id => "hidden_image", :class => "hidden") %>

app/views/drawing/error.html.erb
<p class="flex">Uh-Oh, we couldn't find the drawing you were looking for.</p>
<% link_to "Start a new drawing.".html_safe, @drawing %>

app/views/drawing/show.html.erb
<div class="flex">
  <p>Someone has shared the below static image with you.</p>
  <%= link_to "Start a new drawing!", new_drawing_path() %>
</div>

<div class="flex">
  <%= image_tag(@drawing.imgUrl), alt="#{@drawing.id}.png"%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WebBoard</title>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <a href="/"><h1 class="flex">Collaborative Doodles</h1></a>
  <div class="flex">
    <h3>A project by <a href="http://wsimons.com">Will Simons</a>, <a href="https://www.linkedin.com/in/mikephe">Mike Phe</a>, and <a href="https://www.linkedin.com/in/brianguilardi">Brian Guilliardi.</a></h3>
  </div>
  <div class="flex">
    <div class="button" id="share-button">Share Drawing</div>
    <div class="button" id="clear-button">Reset</div>
  </div>
  <div class="flex">
    <div class="flex-vertical">
      <div class='color' id='c1'></div>
      <div class='color' id='c2'></div>
      <div class='color' id='c3'></div>
      <div class='color' id='c4'></div>
      <div class='color' id='c5'></div>
      <div class='color' id='c6'></div>
      <div class='color' id='c7'></div>
      <div class='color' id='c8'></div>
      <div class='color' id='c9'></div>
      <div class='color' id='c10'></div>
      <div class='color' id='c11'></div>
      <div class='color' id='c12'></div>
      <div class='color' id='c13'></div>
      <div class='color' id='c14'></div>
      <div class='color' id='c15'></div>
      <div class='color' id='c16'></div>
      <div class='color' id='c17'></div>
      <div class='color' id='c18'></div>
      <div class='color' id='c19'></div>
      <div class='color' id='c20'></div>
    </div>
    <div class="canvas-container">
      <canvas width="600px" height="600px"></canvas>
    </div>
    <div class="flex-vertical">
        <div class='size'>
          <div class='inner-size' id='s1'></div>
        </div>
        <div class='size'>
          <div class='inner-size' id='s2'></div>
        </div>
        <div class='size'>
          <div class='inner-size' id='s3'></div>
        </div>
        <div class='size'>
          <div class='inner-size' id='s4'></div>
        </div>
        <div class='size'>
          <div class='inner-size' id='s5'></div>
        </div>
        <div class='size'>
          <div class='inner-size' id='s6'></div>
        </div>
        <div class='size'>
          <div class='inner-size' id='s7'></div>
        </div>
        <div class='size'>
          <div class='inner-size' id='s8'></div>
        </div>
        <div class='size'>
          <div class='inner-size' id='s9'></div>
        </div>
        <div class='size'>
          <div class='inner-size' id='s10'></div>
        </div>
    </div>
  </div>
<%= yield %>

</body>
</html>

app/views/layouts/blank.html.erb
<a href="/"><h1 class="flex">Collaborative Doodles</h1></a>
  <div class="flex">
    <h3>A project by <a href="http://wsimons.com">Will Simons</a>, <a href="">Mike Phe</a>, and <a href="">Brian Guilliardi.</a></h3>
  </div>
<%= yield %>

app/views/layouts/static.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WebBoard</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <a href="/"><h1 class="flex">Collaborative Doodles</h1></a>
  <div class="flex">
    <h3>A project by <a href="http://wsimons.com">Will Simons</a>, <a href="">Mike Phe</a>, and <a href="">Brian Guilliardi.</a></h3>
  </div>
<%= yield %>

</body>
</html>

app/views/web_board/board.html.erb
<div class="flex">
  <h1>Ruby WebBoard</h1>
</div>

<div class="flex">
  <button id="share-button">Share Drawing</button>
  <button id="clear-button">Reset</button>
  <input id="color-picker" type="color" name="color" value="#bada55" />
  <input id="size-picker" type="range" name="strokesize" value="5" min="1" max="10" />
</div>
<div class="flex">
  <div class="canvas-container">
    <canvas width="600px" height="600px"></canvas>
  </div>
</div>